language: node_js
node_js:
  - "stable"
  - "5.9.0"
  - "5.8.0"
  - "5.6.0"
  - "4.4.2"
  - "0.12"
  - "iojs"

install: "npm install && npm install --only=dev"
before_script: "npm install -g mocha"
script: "npm test"
