language: node_js
node_js:
  - "stable"
  - "5.9.0"
  - "5.8.0"
  - "5.6.0"
  - "4.4.2"

install: "npm install && npm install --only=dev"
before_script: "npm install -g mocha"
script: "npm test"
after_script: "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
