// Generated by CoffeeScript 1.10.0

/**
 * Buildup script for server
 */


/**
 * Module dependencies
 */
const fs = require('fs');
const path = require('path');
const YAML = require('yamljs');
/**
 * Server class
 * Creates a new server
 *
 * @param dir {String} Directory of build
 * @class
 */
function Server(dir) {
  this.dir = path.resolve(dir);
}

/**
 * Register the server's name
 * @param name {String} Name of server
 */
Server.prototype.nameServer = (name) => {
  this.name = name
};

/**
 * Load config
 * @param config {String} Config from a file
 * @param options {Object} Options
 */
Server.prototype.loadConfig = function (config, options) {
  // Is server named?
  if (typeof options !== 'undefined' && typeof options.file !== 'undefined' && options.file === true) {
    // file
    if (path.resolve(config) !== path.normalize(config)) {
      config = path.join(this.dir, config);
      this.configFile = config;
    } else {
      this.configFile = config;
    }
    if (options.type === 'yml' || options.type === 'yaml' || options.type === 'YAML' || options.type === 'YML') {
      this.config = YAML.parse(fs.readFileSync(this.configFile));
      return this.config;
    } else if (options.type === 'json' || options.type === 'JSON') {
      this.config = require(this.configFile);
      return this.config;
    }
  } else {
    // Not a file
    this.config = config;
    return this.config;
  }
};

// test
var ser = new Server('..')
ser.loadConfig(`${__dirname}/../servertest/buildup.json`, { file: true, type: 'json' })
console.log(ser);
module.exports = {
    Server: Server
};
