// Generated by CoffeeScript 1.10.0

/**
 * Buildup script for server
 */


/**
 * Module dependencies
 */
const fs = require('fs');
/**
 * Server class
 * Creates a new server
 *
 * @param dir {String} Directory of build
 * @class
 */
function Server(dir) {
  this.dir = path.resolve(dir);
}

/**
 * Register the server's name
 * @param name {String} Name of server
 */
Server.prototype.nameServer = (name) => {
  this.name = name
};



module.exports = {
    Server: Server
  };
